In [1]:
!pip install gensim

In [2]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [3]:
import pandas as pd

In [4]:
datasett = pd.read_csv('finalreview.csv')

In [5]:
datasett

review  label
0   loved the movie action, best performance by ev...      1
1           It was a good movie, a blockbuster cinema      1
2                        I loved the movie and acting      1
3           best part was acting, awesome performance      1
4                                Total waste of money      0
5   Poor storyline, and very bad performance by th...      0
6   I Give 9/10 for this one.9/10 because,Editing ...      1
7                  First half is very slow and boring      0
8        Songs are the best part of movie, I liked it      1
9       such a waste of time and money, rubbish movie      0
10            I will give it a big zero, what a waste      0
11                      Total overacting by the leads      0
12  No doubt. This film is the changing face for f...      1
13  The best of all Indian movies.Nothing can be c...      1
14  movie is known for his suspenses and thriller....      0
15  Good Story ,Great Visuals,best part is there a...      1
16  Worst movie of the  decade. i am giving 1 star...      0
17        A very illogical action sequences as usual.      0
18  Remarkable direction, outstanding acting, monu...      1
19             Meaningless, in appropriate, boring!!!      0
20  This is undoubtedly one of the worst big budge...      0
21  This was 3rd class acting and screen work. I w...      0
22  The worst movie I've ever seen in my whole lif...      0
23  An epic milestone in film industry!! I am very...      1
24  Fabulous work done by lead,we can't get bored ...      1
25   this movie is a win for the whole film industry.      1
26  the performances was very average, actors lite...      0
27      this movie is ridiculous,very BAD BAD BAD BAD      0
28                          garbage movie, 0 out of 5      0
29  performance is mindblowing. The depiction of a...      1
30  fantastic movie writting, best performance by ...      1
31  superb flop movie i ever seen in my life loser...      0
32  only stunt is not important acting is also req...      0
33  This movie is a very horrible and a worst movi...      0
34  lead acting was like a fool, rubbish story, ve...      0
35            Game Changer, Mass Cinematic Brilliance      1
36  It was a mind-blowing experience to watch such...      1
37  literally the background movie gave me goosebu...      1
38   this movie should be banned, very disrespectfull      0
39  This movie is a masterpiece with a unique stor...      1
40  This is the worst movie I've ever seen in my w...      0
41  ONE OF THE MOST POWERFUL MOVIES I HAVE EVER WA...      1
42  This movie just is a disaster,weak narrative a...      0
43  Excellent Story, best screen play,great  direc...      1
44  Very very flop movie.worst worst worst film in...      0
45  The best Indian action film,absolutely brillia...      1
46  this movie is one of my favorites, engaging mu...      1
47  The action was so unnecessary ,dialoges were v...      0
48  It is the best best best great movie I have ev...      1
49  This movie is a very horrible and a worst movi...      0

In [27]:
from nltk.corpus import stopwords
import re
corpus = []
for i in range(0, 29):
    review = re.sub('[^a-zA-Z]', ' ', datasett['review'][i])
    review = review.lower()
    review = review.split() 
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [7]:
corpus

['loved movie action best performance every actor',
 'good movie blockbuster cinema',
 'loved movie acting',
 'best part acting awesome performance',
 'total waste money',
 'poor storyline bad performance lead',
 'give one editing much fast except everything felt right place',
 'first half slow boring',
 'song best part movie liked',
 'waste time money rubbish movie',
 'give big zero waste',
 'total overacting lead',
 'doubt film changing face film industry every people put hard work effort',
 'best indian movie nothing compared',
 'movie known suspense thriller missing film really bad',
 'good story great visuals best part many character film really increase curiosity audience acting awesome',
 'worst movie decade giving star',
 'illogical action sequence usual',
 'remarkable direction outstanding acting monumental narration unthinkable screenplay striking action sequence',
 'meaningless appropriate boring',
 'undoubtedly one worst big budget commercial movie seen',
 'rd class acting 

In [8]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

sentences = []
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        sentences.append(simple_preprocess(sent))

In [9]:
sentences

[['loved', 'movie', 'action', 'best', 'performance', 'every', 'actor'],
 ['good', 'movie', 'blockbuster', 'cinema'],
 ['loved', 'movie', 'acting'],
 ['best', 'part', 'acting', 'awesome', 'performance'],
 ['total', 'waste', 'money'],
 ['poor', 'storyline', 'bad', 'performance', 'lead'],
 ['give',
  'one',
  'editing',
  'much',
  'fast',
  'except',
  'everything',
  'felt',
  'right',
  'place'],
 ['first', 'half', 'slow', 'boring'],
 ['song', 'best', 'part', 'movie', 'liked'],
 ['waste', 'time', 'money', 'rubbish', 'movie'],
 ['give', 'big', 'zero', 'waste'],
 ['total', 'overacting', 'lead'],
 ['doubt',
  'film',
  'changing',
  'face',
  'film',
  'industry',
  'every',
  'people',
  'put',
  'hard',
  'work',
  'effort'],
 ['best', 'indian', 'movie', 'nothing', 'compared'],
 ['movie',
  'known',
  'suspense',
  'thriller',
  'missing',
  'film',
  'really',
  'bad'],
 ['good',
  'story',
  'great',
  'visuals',
  'best',
  'part',
  'many',
  'character',
  'film',
  'really',
  'in

In [10]:
import gensim
model=gensim.models.Word2Vec(sentences,window=3,min_count=1)

In [11]:
model.corpus_count

29

In [12]:
model.wv.index_to_key

['movie',
 'best',
 'bad',
 'film',
 'acting',
 'performance',
 'part',
 'lead',
 'waste',
 'industry',
 'boring',
 'worst',
 'work',
 'action',
 'whole',
 'indian',
 'great',
 'sequence',
 'big',
 'time',
 'really',
 'screenplay',
 'loved',
 'seen',
 'money',
 'one',
 'total',
 'every',
 'actor',
 'good',
 'awesome',
 'give',
 'changing',
 'face',
 'cinema',
 'editing',
 'people',
 'doubt',
 'hard',
 'blockbuster',
 'effort',
 'nothing',
 'compared',
 'put',
 'zero',
 'overacting',
 'much',
 'fast',
 'except',
 'everything',
 'felt',
 'right',
 'suspense',
 'place',
 'first',
 'half',
 'slow',
 'song',
 'liked',
 'storyline',
 'rubbish',
 'poor',
 'known',
 'garbage',
 'thriller',
 'watching',
 'disappointed',
 'ever',
 'life',
 'nonsense',
 'epic',
 'milestone',
 'proud',
 'fabulous',
 'done',
 'get',
 'bored',
 'background',
 'screen',
 'music',
 'cinematography',
 'amazing',
 'win',
 'average',
 'literally',
 'walked',
 'talked',
 'acted',
 'like',
 'robot',
 'extremely',
 'class',

In [13]:
from gensim.models import KeyedVectors
word_vectors = model.wv
word_vectors.save("word2vec.wordvectors")

wv = KeyedVectors.load("word2vec.wordvectors")
vector = wv['worst']

In [14]:
vector

array([ 9.7802887e-03,  8.1691816e-03,  1.2762035e-03,  5.0976058e-03,
        1.4070637e-03, -6.4661731e-03, -1.4169702e-03,  6.4737783e-03,
       -4.6283016e-03, -3.9985883e-03,  4.9228244e-03,  2.7162295e-03,
       -1.8412578e-03, -2.8709208e-03,  5.9995907e-03, -5.7205064e-03,
       -3.2234399e-03, -6.4902911e-03, -4.2465297e-03, -8.5991677e-03,
       -4.4568083e-03, -8.5190870e-03,  1.4122641e-03, -8.6348727e-03,
       -9.9129276e-03, -8.2063852e-03, -6.7810114e-03,  6.6846199e-03,
        3.7707100e-03,  3.6329692e-04, -2.9542963e-03, -7.4233352e-03,
        5.3763355e-04,  4.8847735e-04,  1.9537541e-04,  8.5930963e-04,
        7.8601495e-04, -7.1654154e-05, -8.0049559e-03, -5.8858236e-03,
       -8.3860680e-03, -1.3135688e-03,  1.8097514e-03,  7.4178926e-03,
       -1.9480338e-03, -2.3379966e-03,  9.4815632e-03,  7.8400117e-05,
       -2.3969549e-03,  8.6077750e-03,  2.6818896e-03, -5.3472142e-03,
        6.5865959e-03,  4.4976361e-03, -7.0453193e-03, -3.2886473e-04,
      

In [15]:
wv['movie']

array([-5.3341099e-04,  2.4877596e-04,  5.1067229e-03,  9.0310713e-03,
       -9.3028788e-03, -7.1458262e-03,  6.4698206e-03,  9.0199215e-03,
       -5.0632064e-03, -3.7538598e-03,  7.3775849e-03, -1.5443944e-03,
       -4.5120013e-03,  6.5862411e-03, -4.8559140e-03, -1.8092741e-03,
        2.8728831e-03,  9.8923687e-04, -8.3175460e-03, -9.4934739e-03,
        7.3423120e-03,  5.0478713e-03,  6.7715994e-03,  7.2577427e-04,
        6.3490258e-03, -3.4283239e-03, -9.8952313e-04,  5.7464736e-03,
       -7.5430633e-03, -3.9668255e-03, -7.4898889e-03, -9.0812804e-04,
        9.5868083e-03, -7.3320772e-03, -2.3491837e-03, -1.9063272e-03,
        8.0650076e-03, -5.9145698e-03,  4.1875726e-05, -4.7986852e-03,
       -9.6011078e-03,  5.0092358e-03, -8.7747844e-03, -4.3919501e-03,
       -3.9211223e-05, -3.3092278e-04, -7.6658777e-03,  9.6039977e-03,
        4.9739932e-03,  9.2564505e-03, -8.1743533e-03,  4.4893669e-03,
       -4.1501140e-03,  7.9350447e-04,  8.5513070e-03, -4.5030508e-03,
      

In [16]:
wv['great']

array([ 1.2923613e-03, -9.7971987e-03,  4.5714914e-03, -5.1193731e-04,
        6.3125924e-03,  1.7667389e-03, -3.1173185e-03,  7.8051090e-03,
        1.5226129e-03,  4.3091608e-05, -4.6093585e-03, -8.4702531e-03,
       -7.7684894e-03,  8.6929509e-03, -8.9200567e-03,  9.0421522e-03,
       -9.2776166e-03, -2.7083728e-04, -1.9206842e-03, -8.9661228e-03,
        8.6443573e-03,  6.7567420e-03,  3.0339879e-03,  4.8114071e-03,
        1.2912857e-04,  9.4206631e-03,  7.0081679e-03, -9.8710321e-03,
       -4.4466816e-03, -1.3150929e-03,  3.0609439e-03, -4.3218760e-03,
        1.4747735e-03, -7.8537660e-03,  2.7754903e-03,  4.7101504e-03,
        4.9491636e-03, -3.1787534e-03, -8.4213382e-03, -9.2458623e-03,
       -7.2274607e-04, -7.3336274e-03, -6.8333233e-03,  6.1170771e-03,
        7.1818042e-03,  2.0813837e-03, -7.9199551e-03, -5.6905122e-03,
        8.0638761e-03,  3.9371871e-03, -5.2492614e-03, -7.3872320e-03,
        7.5327558e-04,  3.4531318e-03,  2.1022870e-03,  3.0823813e-03,
      

In [17]:
wv.similar_by_word('movie')

[('proud', 0.29040318727493286),
 ('many', 0.23207567632198334),
 ('great', 0.22010105848312378),
 ('industry', 0.21900494396686554),
 ('watching', 0.20550432801246643),
 ('actor', 0.19623330235481262),
 ('place', 0.17265571653842926),
 ('put', 0.17074157297611237),
 ('awesome', 0.15295805037021637),
 ('cinema', 0.14276577532291412)]

In [18]:
import numpy as np
def sentence_vector(sent):
    doc = [word for word in sent.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [25]:
sentence_vector(datasett['review'].values[20])

array([ 0.00422246, -0.0008309 ,  0.00155276,  0.00049586, -0.00167588,
        0.00012432,  0.00054   ,  0.00472425, -0.00258039, -0.00141265,
       -0.00065444,  0.00072133, -0.00094032,  0.00035494,  0.0006083 ,
        0.00081437,  0.00107797, -0.00161981,  0.001287  , -0.00065216,
        0.00038056, -0.00222888, -0.00123109, -0.00538537, -0.00221802,
       -0.00137051, -0.00424015,  0.00056689,  0.00199476, -0.00040052,
        0.00512448, -0.00135929, -0.00306951, -0.00178853, -0.00118769,
        0.00161797,  0.00322041, -0.00207535, -0.00412099, -0.00260661,
        0.00177594, -0.00053891,  0.00425165,  0.00152007, -0.00187223,
       -0.00189343, -0.00133834, -0.00140753,  0.00288288, -0.00042716,
        0.0013594 ,  0.00101374,  0.00133179,  0.00122224, -0.0007652 ,
        0.00293508, -0.00217569,  0.00295454, -0.00077916, -0.00118152,
       -0.00103254,  0.00247701,  0.00262405,  0.00285418, -0.00213168,
        0.00382419,  0.00380276, -0.00031127, -0.00196237,  0.00

In [20]:
from tqdm import tqdm

In [28]:
final = []
for s in tqdm(datasett['review'].values):
    final.append(sentence_vector(sent))

100%|██████████| 50/50 [00:00<00:00, 5955.45it/s]


In [29]:
final

[array([ 7.43024983e-04,  4.25107777e-03, -1.59201445e-03,  1.34951435e-04,
        -4.92114574e-03, -4.52004652e-03,  2.06570048e-03,  4.20881482e-03,
        -5.06602973e-03, -5.89339016e-03,  7.81477056e-03, -2.44595460e-03,
        -3.68301850e-03,  2.46823975e-03, -3.03631881e-03, -5.50165167e-03,
         5.33314713e-04, -1.81538111e-04,  1.67842954e-04, -8.72202590e-03,
         1.29262521e-03,  1.58216385e-03,  4.82329074e-03, -2.64293887e-03,
         3.97485681e-04, -5.69568388e-03,  2.26937467e-03, -1.48302456e-03,
        -5.39204944e-03, -1.83968840e-03, -3.01764300e-03, -5.42796496e-03,
         9.11686569e-03, -4.69514774e-03, -9.97238792e-04, -5.35369013e-03,
        -4.97736037e-05, -1.07279397e-03,  2.02972395e-03, -9.08302376e-04,
        -1.87670439e-03, -9.66013642e-04, -5.00400132e-03, -3.55851371e-03,
        -7.20599608e-04,  2.07991758e-03, -3.15087684e-03,  1.08078774e-03,
         4.10698634e-03,  7.75713660e-03, -7.13683944e-03,  3.85851273e-03,
        -4.2